#!/usr/bin/env python3
"""
Build guard run by .github/workflows/android.yml against the final ProtoHax jar (the one that is packaged
into the APK). Every check below corresponds to a real failure that happened or was ruled out with evidence:

  * the registry data of the `mcpedata` git submodule must be inside the jar. Without it
    MappingProvider.<init> throws a NullPointerException, ItemMapping$Provider fails to initialise,
    GameSession() throws and the app's MinecraftRelay object dies with "NoClassDefFoundError: <obfuscated>"
    (the "M2.g" error seen at runtime).
  * the Bedrock v844 codec must be present, the relay must be configured for it (not for v2193) and the
    block / item registry data of protocol 844 must exist (otherwise a 1.21.111 session silently uses the
    1.20.10 data of the mcpedata submodule).
  * no class may still reference java.awt.Color (Android has no java.awt).
  * the relay's RakNet client GUID must be negative like the vanilla client's (go-raknet based servers - Dragonfly
    and many community servers - silently ignore positive ones, so about every second connect would time out).
  * the Microsoft OAuth fix (authorization_code on first login, refresh_token afterwards) must be in the jar.

usage: verify_jar.py <ProtoHax jar>
"""
import json
import sys
import zipfile

jar = zipfile.ZipFile(sys.argv[1])
names = set(jar.namelist())
problems = []

# 1. registry data from the mcpedata submodule (+ the bundled music file)
for asset in (
    "assets/mcpedata/blocks/index.json",
    "assets/mcpedata/items/index.json",
    "assets/mcpedata/item_tags.json",
    "assets/mcpedata/legacy_block_states.nbt.gz",
    "assets/music.nbs",
):
    if asset not in names:
        problems.append("missing resource %s (is the mcpedata submodule checked out?)" % asset)

# 1b. registry data of protocol 844 (generated by apply_android_patches.py from pmmp/BedrockData)
for asset in (
    "assets/mcpedata/blocks/canonical_block_states_844.nbt.gz",
    "assets/mcpedata/items/runtime_item_states_844.json",
    "assets/mcpedata/block_hardness.json",
):
    if asset not in names:
        problems.append("missing protocol 844 registry data %s" % asset)
for index in ("assets/mcpedata/blocks/index.json", "assets/mcpedata/items/index.json"):
    if index in names and 844 not in json.loads(jar.read(index)):
        problems.append("%s does not list protocol 844" % index)

# 2. protocol v844
for cls in (
    "org/cloudburstmc/protocol/bedrock/codec/v844/Bedrock_v844.class",
    "org/cloudburstmc/protocol/bedrock/codec/compat/BedrockCompat.class",
    "dev/sora/relay/session/listener/RelayListenerAutoCodec.class",
):
    if cls not in names:
        problems.append("missing class %s" % cls)


def raw(name):
    return jar.read(name) if name in names else b""


relay = raw("dev/sora/relay/MinecraftRelay.class")
if b"Bedrock_v844" not in relay:
    problems.append("dev.sora.relay.MinecraftRelay is not configured for the v844 codec")
if b"Bedrock_v2193" in relay:
    problems.append("dev.sora.relay.MinecraftRelay still advertises the v2193 codec")
session = raw("dev/sora/relay/game/GameSession.class")
if b"1.21.111" not in session or b"1.26.50" in session:
    problems.append("GameSession.RECOMMENDED_VERSION is not 1.21.111")

# 2b. the relay's RakNet client GUID must be negative (Long.MIN_VALUE is OR-ed in: a CONSTANT_Long 0x8000000000000000)
initializer = raw("dev/sora/relay/MinecraftRelay$BedrockRelayInitializer.class")
if b"\x05\x80\x00\x00\x00\x00\x00\x00\x00" not in initializer:
    problems.append("the relay's RakNet client GUID is not forced negative (go-raknet servers reject positive GUIDs)")

# 3. java.awt.Color must be gone, its replacement present
if "dev/sora/relay/compat/Color.class" not in names:
    problems.append("dev.sora.relay.compat.Color is missing")
offenders = [
    n for n in names
    if n.endswith(".class") and not n.startswith("META-INF/") and b"java/awt/Color" in jar.read(n)
]
if offenders:
    problems.append("%d classes still reference java.awt.Color, e.g. %s" % (len(offenders), sorted(offenders)[:5]))

# 4. the Microsoft OAuth fix (patched into XboxDeviceInfo by android.yml): first login = authorization_code,
#    later logins = refresh_token
oauth = raw("dev/sora/relay/session/listener/xbox/XboxDeviceInfo.class")
for needle in (b"exchangeAuthorizationCode", b"refreshAccessToken", b"authorization_code", b"refresh_token"):
    if needle not in oauth:
        problems.append("OAuth fix missing: XboxDeviceInfo does not contain %s" % needle.decode())

if problems:
    print("ProtoHax jar verification FAILED:")
    for p in problems:
        print("  - " + p)
    sys.exit(1)
print("ProtoHax jar verification passed: registry assets present, v844 configured, no java.awt.Color left, OAuth fix present")
